### ISSUE TITLE
CSP Error in TYPO3 v12

### ISSUE THREAD

**Issue by 80Quattro** [studiomitte/friendlycaptcha-typo3#6]
In TYPO3 v12, if Content Security Policy is enabled, the FriendlyCaptcha Template scripts / styles are not correctly loaded.

Appropriate directives need to be added in csp.yaml file.

**Comment by 80Quattro** [comment]
Something like that works for us:
```yml
# Inherits default site-unspecific frontend policy mutations (enabled per default)
inheritDefault: true
mutations:
  - mode: set
    directive: 'script-src'
    sources:
      - "'self'"
      - "'unsafe-inline'"

  - mode: set
    directive: 'default-src'
    sources:
      - "'self'"
      - "'unsafe-inline'"

  - mode: set
    directive: 'worker-src'
    sources:
        - 'blob:'
      
  - mode: extend
    directive: 'connect-src'
    sources:
      - 'https://*.friendlycaptcha.eu'
```
